// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Cs-_Xn5oeXXZ9BPOm29J3VlFV3s1D0I',
    appId: '1:834513621056:web:496c1f168055b7cd768fa5',
    messagingSenderId: '834513621056',
    projectId: 'water-distribution-fdb23',
    authDomain: 'water-distribution-fdb23.firebaseapp.com',
    storageBucket: 'water-distribution-fdb23.firebasestorage.app',
    measurementId: 'G-86Z7V4GL8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0yAyLxoZyF_GBFc7TnxnlsylEgi2q9aw',
    appId: '1:834513621056:android:99554f368553397c768fa5',
    messagingSenderId: '834513621056',
    projectId: 'water-distribution-fdb23',
    storageBucket: 'water-distribution-fdb23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapjl-13wtAOdY1Vma8zP2o0ypc-x8OJM',
    appId: '1:834513621056:ios:5709d219290319bd768fa5',
    messagingSenderId: '834513621056',
    projectId: 'water-distribution-fdb23',
    storageBucket: 'water-distribution-fdb23.firebasestorage.app',
    iosBundleId: 'com.example.waterDistributionManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCapjl-13wtAOdY1Vma8zP2o0ypc-x8OJM',
    appId: '1:834513621056:ios:5709d219290319bd768fa5',
    messagingSenderId: '834513621056',
    projectId: 'water-distribution-fdb23',
    storageBucket: 'water-distribution-fdb23.firebasestorage.app',
    iosBundleId: 'com.example.waterDistributionManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Cs-_Xn5oeXXZ9BPOm29J3VlFV3s1D0I',
    appId: '1:834513621056:web:291056a5399a535b768fa5',
    messagingSenderId: '834513621056',
    projectId: 'water-distribution-fdb23',
    authDomain: 'water-distribution-fdb23.firebaseapp.com',
    storageBucket: 'water-distribution-fdb23.firebasestorage.app',
    measurementId: 'G-Z9XQVJTF34',
  );
}
